---
development:
  demurrage: '1'
  commission: '1'
  master_account: wasilew
  accrual_frequency: weekly
  additional_amount: '9'
production:
  demurrage: '1'
  commission: '1'
  master_account: wasilew
  accrual_frequency: weekly
  additional_amount: '10'
