---
development:
  demurrage: '1'
  commission: '1'
  master_account: wasilew
  accrual_frequency: weekly
  additional_amount: '1000'
production:
  demurrage: '1'
  commission: '1'
  master_account: wasilew
  accrual_frequency: weekly
  additional_amount: '1000'
